export const PRICING_DATA = [
  {
    note: '',
    subtitle: 'Basic',
    type: 1,
    currency: '$',
    number: 9,
    time: 'month',
    text: 'Beautifully simple project planning',
    btn: 'Start free trial',
    details: {
      category: 'Basic',
      stage: 'Core features',
      view: 'See features',
      options: [
        '10 Boards per Team',
        'Unlimited Cards',
        'Unlimited Lists',
        '10MB per File Attachment',
      ],
    },
  },
  {
    note: 'most popular',
    subtitle: 'Premium',
    type: 2,
    currency: '$',
    number: 19,
    time: 'month',
    text: 'Declutter your mind and save time with Premium.',
    btn: 'Start free trial',
    details: {
      category: 'Premium',
      view: 'See features',
      options: [
        'Unlimited Boards per Team',
        'Unlimited Cards',
        'Unlimited Lists',
        '250MB per File Attachment',
        'Advanced Checklists',
        'Priority Support',
      ],
    },
  },
  {
    note: '',
    subtitle: 'Business',
    type: 3,
    src: 'assets/img/box.png',
    srcset: 'assets/img/box@2x.png 2x',
    text: 'For large business and team. Contact sale!',
    btn: 'Contact Sale',
    details: {
      category: 'Business',
      view: 'See features',
      options: [
        'Unlimited Boards per Team',
        'Unlimited Cards',
        'Unlimited Lists',
        '1GB per File Attachment',
        '100+ App Integrations',
        'Unlimited Command runs',
        'Priority Support',
      ],
    },
  },
];
